[project]
name = "renewal"
version = "0.1.0"
description = "Add a short description here"
authors = ["David Shipman <dshipman@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "osx-arm64", "linux-64"]

[tasks]

[dependencies]
python = "3.10.*"
pytables = "==3.8.0"
pyproj = "*"
dm-tree = "*"
rasterio = "*"

[pypi-dependencies]
emu_renewal = { path = "./code", editable = true}
jupyterlab = ">=4.3.5, <5"
ipywidgets = ">=8.1.5, <9"
pandas = "==2.2.3"
jupyterlab-git = ">=0.50.2, <0.51"
kaleido = ">=0.2.1, <0.3"
openpyxl = ">=3.1.5, <4"
pycountry-convert = ">=0.7.2, <0.8"
