from typing import Union, List, Tuple
from typing import NamedTuple
from jax import lax, vmap, Array, numpy as jnp
from jax.experimental import sparse
from datetime import datetime
import pandas as pd
import numpy as np
from warnings import warn
import copy

from summer2.utils import Epoch

from emu_renewal.process import sinterp, MultiCurve
from emu_renewal.distributions import Dens
from emu_renewal.utils import format_date_for_str, round_sigfig, get_combs


ModelResult = dict[str, Array]


def get_dests(
    strain_map: np.ndarray,
) -> np.ndarray:
    """For a given set of immunity combinations
    (generated by get_combs), create a matrix (dests)
    that specifies which immunity profile you would
    transition to if infected by the strain represented by
    the row of the matrix.

    Example:
        First row of strain_map is [False, False] and
        second row is [False, True], element [0, 1]
        of dests will be 1.

    Args:
        strain_map: The possible immunity combinations

    Returns:
        The matrix described above
    """
    dests = np.zeros_like(strain_map, dtype=int)

    # Iterate through strains (rows of dests matrix)
    for s in range(strain_map.shape[0]):

        # Iterate through columns of matrix
        for i, imm in enumerate(strain_map.T):

            # Destination strain history
            dest = copy.copy(imm)
            dest[s] = True

            # Find its location within the mapping matrix
            dests[s, i] = np.where((strain_map == dest[:, None]).all(axis=0))[0][0]

    return dests


def get_trans_mats(dests: np.ndarray):
    """Get transition matrix for moving population
    based on destinations specified in get_dests above.

    Args:
        dests: Destination matrix

    Returns:
        Transition matrix
    """
    n_strains = dests.shape[0]
    n_rec_groups = dests.shape[1]
    trans_mats = []
    for s in range(n_strains):
        trans_mat = np.zeros((n_rec_groups, n_rec_groups))
        for source, dest in enumerate(dests[s]):
            trans_mat[source, dest] += 1.0
            trans_mat[source, source] -= 1.0
        trans_mats.append(sparse.BCOO.fromdense(trans_mat))
    return trans_mats


class RenewalState(NamedTuple):
    incidence: jnp.array
    suscept: float


class MultistrainState(NamedTuple):
    incidence: jnp.array
    suscept: jnp.array


class RenewalModel:
    def __init__(
        self,
        population: float,
        start: Union[datetime, int],
        end: Union[datetime, int],
        proc_update_freq: int,
        proc_fitter: MultiCurve,
        dens_obj: Dens,
        window_len: int,
        init_series: Union[pd.Series, np.array],
        reporting_dist: Dens,
    ):
        """Standard renewal model object.

        Args:
            population: Starting population value
            start: Start time for the analysis period (excluding run-in)
            end: End time for the analysis period
            proc_update_freq: Frequency with with the vairable process is updated
            proc_fitter: The object containing the method for fitting to the variable process series
            dens_obj: Generation time distribution
            window_len: How far to look back in calculating the renewal process
            init_series: Initialisation series prior to analysis start
        """

        # Initialising series
        if len(init_series) < window_len:
            warn("Padding initialisation series with zeroes because shorter than window")
            self.init_series = np.concatenate(
                [np.zeros(window_len - len(init_series)), init_series]
            )
        elif len(init_series) > window_len:
            warn("Trimming initialisation series because longer than window")
            self.init_series = jnp.array(init_series[-window_len:])
        else:
            self.init_series = jnp.array(init_series)
        self.init_length = len(self.init_series)

        # Times
        self.epoch = Epoch(start) if isinstance(start, datetime) else None
        self.start = self.process_time_req(start)
        self.end = self.process_time_req(end)
        self.model_times = jnp.arange(self.start, self.end + 1)
        self.description = {
            "Fixed parameters": (
                f"The main analysis period runs from {format_date_for_str(start)} "
                f"to {format_date_for_str(end)}, "
                f"with a preceding initialisation period of {self.init_length} days. "
            )
        }

        # Population
        self.pop = population
        self.description[
            "Fixed parameters"
        ] += f"The starting model population is {round_sigfig(population / 1e6, 2)} million persons. "

        # Process
        self.proc_update_freq = proc_update_freq
        self.x_proc_vals = jnp.arange(self.end, self.start, -self.proc_update_freq)[::-1]
        self.x_proc_data = sinterp.get_scale_data(self.x_proc_vals)
        self.proc_fitter = proc_fitter
        self.process_start = int(self.x_proc_vals[0])
        self.description["Variable process"] = (
            "Each x-value for the requested points in the variable process "
            "are set at evenly spaced intervals through the analysis period "
            f"spaced by {self.proc_update_freq} days and "
            "ending at the analysis end time. "
        )
        if self.start < self.process_start:
            self.description["Variable process"] = (
                "Because the analysis period is not an exact multiple "
                "of the duration of a process interval, "
                "the variable process only starts from day "
                f"{self.process_start} of the analysis. "
            )
        self.describe_process()

        # Generation interval
        self.dens_obj = dens_obj
        self.description["Generation times"] = self.dens_obj.get_desc()
        self.window_len = window_len
        self.description["Generation times"] += (
            "The generation interval for all calculations "
            f"is truncated from {window_len} days onwards "
            "on the assumption that the distribution's density "
            "has reached negligible values once this period has elapsed. "
        )

        # Renewal process
        self.describe_renewal()

        # Reporting delay
        self.report_dist = reporting_dist
        self.describe_reporting()
        self.description["Reporting"] += self.report_dist.get_desc()
        self.describe_weekly_sum()

    def process_time_req(
        self,
        req: Union[datetime, int],
    ) -> int:
        """Sort out a user requested date.

        Args:
            req: The request

        Raises:
            ValueError: If neither date nor int

        Returns:
            The request converted to int according to the model's epoch
        """
        msg = "Time data type not supported"
        if isinstance(req, int):
            return req
        elif isinstance(req, datetime):
            return int(self.epoch.dti_to_index(req))
        else:
            raise ValueError(msg)

    def fit_process_curve(
        self,
        y_proc_req: List[float],
        rt_init,
    ) -> jnp.array:
        """See describe_process below.

        Args:
            y_proc_req: The submitted log values for the variable process

        Returns:
            The values of the variable process at each model time
        """
        y_proc_vals = jnp.cumsum(jnp.concatenate([jnp.array((rt_init,)), y_proc_req]))
        y_proc_data = sinterp.get_scale_data(y_proc_vals)
        cos_func = vmap(self.proc_fitter.get_multicurve, in_axes=(0, None, None))
        return jnp.exp(cos_func(self.model_times, self.x_proc_data, y_proc_data))

    def describe_process(self):
        self.description["Variable process"] += self.proc_fitter.get_description()
        self.description["Variable process"] += (
            "The parameters for the variable process are explored as "
            "the update of each process value relative to the preceding value. "
            "Each of the parameters for the variable process is exponentiated, "
            "such that these parameters are explored in the log-transformed space. "
        )

    def get_output_from_inc(
        self,
        full_inc: jnp.array,
        report_mean: float,
        report_sd: float,
        cdr: float,
    ) -> jnp.array:
        """Apply an observation model as a convolution to calculate an epidemiological output series.

        Args:
            full_inc: The full incidence series including the initialisation
            report_mean: Mean delay to reporting
            report_sd: Standard deviation of delay to reporting
            cdr: Case detection/ascertainment proportion

        Returns:
            Output from start of initialisation to end of model time
        """
        densities = self.dens_obj.get_densities(self.window_len, report_mean, report_sd)
        convolved_cases = jnp.convolve(full_inc, densities) * cdr
        return convolved_cases[: len(full_inc)]

    def describe_reporting(self):
        self.description["Reporting"] = (
            "Notifications are calculated by first convoling "
            "the probability distribution representing the time from "
            "onset of an infection episode to reporting with the "
            "time series of incidence. "
            "This is then multiplied through by the modelled "
            "case detection rate to obtain the final time series "
            "for case notifications. "
        )

    def get_period_output_from_daily(
        self,
        raw_series: jnp.array,
        n_sum_times: int,
    ) -> jnp.array:
        """Sum over a preceding window period to get counts over a period of time.

        Args:
            raw_series: Observations before windowing applied
            n_sum_times: Duration of period for summing

        Returns:
            Summed series
        """
        windower = jnp.array([1.0] * n_sum_times)
        return jnp.convolve(raw_series, windower)[: len(raw_series)]

    def describe_weekly_sum(self):
        self.description["Reporting"] += (
            "Last, weekly case counts are then calculated from this "
            "time series of notifications. "
        )

    def renewal_func(
        self,
        proc: List[float],
        gen_mean: float,
        gen_sd: float,
        cdr: float,
        rt_init: float,
        report_mean: float,
        report_sd: float,
        prop_immune: float = 0.0,
        **kwargs,
    ) -> ModelResult:
        """See describe_renewal

        Args:
            gen_mean: Generation time mean
            gen_sd: Generation time standard deviation
            proc: Values of the variable process
            cdr: Case detection proportion
            rt_init: Initialisation value for variable process
            report_mean: Mean time from incidence to notification
            report_sd: Standard deviation of the time from incidence to notification
            prop_immune: Starting proportion of the population immune

        Returns:
            Epidemiological results of the model run
        """
        full_inc, outputs = self.renew(gen_mean, gen_sd, proc, cdr, rt_init, prop_immune)
        cases = self.get_output_from_inc(full_inc, report_mean, report_sd, cdr)
        outputs["cases"] = cases[self.init_length :]
        weekly_cases = self.get_period_output_from_daily(cases, 7)
        outputs["weekly_cases"] = weekly_cases[self.init_length :]
        seropos = (self.pop - outputs["suscept"]) / self.pop
        outputs["seropos"] = seropos
        return outputs

    def renew(
        self,
        mean: float,
        sd: float,
        proc: List[float],
        cdr: float,
        init: float,
        imm: float,
    ) -> Tuple[float, Array, Array, ModelResult]:
        """Run the renewal process calculations.

        Args:
            mean: Generation time mean
            sd: Generation time standard deviation
            proc: Values of the variable process
            cdr: Case detection proportion
            init: Initialisation value for variable process
            imm: Starting proportion of the population immune

        Returns:
            Starting population value
            Initialisation incidence sequence
            Incidence series
            Object containing the core epi outputs obtained directly from the renewal process
        """
        densities = self.dens_obj.get_densities(self.window_len, mean, sd)
        process_vals = self.fit_process_curve(proc, init)
        init_inc = self.init_series / cdr
        start_pop = self.pop * (1.0 - imm) - jnp.sum(init_inc)
        init_state = RenewalState(init_inc[::-1], start_pop)

        def state_update(state: RenewalState, t) -> tuple[RenewalState, jnp.array]:
            proc_val = process_vals[t - self.start]  # Variable process
            target_inf_rate = (
                (densities * state.incidence).sum() * proc_val / self.pop
            )  # Calculated incidence
            inf_rate = 1.0 - jnp.exp(-target_inf_rate)
            actual_inc = inf_rate * state.suscept
            suscept = state.suscept - actual_inc  # Susceptible depletion
            inc = jnp.concat([jnp.array([actual_inc]), state.incidence[:-1]])  # Move up in matrix
            out = {
                "incidence": actual_inc,
                "suscept": suscept,
                "r_t": proc_val * state.suscept / self.pop,
                "process": proc_val,
            }
            return RenewalState(inc, suscept), out

        end_state, outputs = lax.scan(state_update, init_state, self.model_times)
        full_inc = jnp.concatenate([init_inc, jnp.array(outputs["incidence"])])
        return full_inc, outputs

    def describe_renewal(self):
        self.description["Renewal process"] = (
            "Calculation of the renewal process "
            "consists of multiplying the incidence values for the preceding days "
            "by the reversed generation time distribution values. "
            "This follows a standard formula, "
            "described elsewhere by several groups,[@cori2013; @faria2021] i.e. "
            "$$i_t = R_t\sum_{\\tau<t} i_\\tau g_{t-\\tau}$$\n"
            "$R_t$ is calculated as the product of the proportion "
            "of the population remaining susceptible "
            "and the non-mechanistic random process "
            "generated external to the renewal model. "
            "The susceptible population is calculated by "
            "subtracting the number of new incident cases from the "
            "running total of susceptibles at each iteration. "
            "If incidence exceeds the number of susceptible persons available "
            "for infection in the model, incidence is capped at the "
            "remaining number of susceptibles. "
        )

    def get_description(self) -> str:
        """Compile the description of model.

        Returns:
            Description
        """
        description = ""
        for title, text in self.description.items():
            description += f"\n\n### {title}\n"
            description += text
        return description


class RenewalHospModel(RenewalModel):

    def __init__(
        self,
        population,
        start,
        end,
        proc_update_freq,
        proc_fitter,
        dens_obj,
        window_len,
        init_series,
        reporting_dist,
        discharge_dens,
    ):
        super().__init__(
            population,
            start,
            end,
            proc_update_freq,
            proc_fitter,
            dens_obj,
            window_len,
            init_series,
            reporting_dist,
        )
        self.discharge_dens = discharge_dens

    def get_hosp_occupancy_from_admits(self, full_admits, stay_mean, stay_sd):
        discharge = 1.0 - self.discharge_dens.get_cum_dens(self.window_len, stay_mean, stay_sd)
        return jnp.convolve(full_admits, discharge)[: len(full_admits)]

    def renewal_func(
        self,
        proc: List[float],
        gen_mean: float,
        gen_sd: float,
        cdr: float,
        ifr: float,
        rt_init: float,
        report_mean: float,
        report_sd: float,
        death_mean: float,
        death_sd: float,
        admit_mean: float,
        admit_sd: float,
        stay_mean: float,
        stay_sd: float,
        har: float,
        prop_immune: float = 0.0,
        **kwargs,
    ) -> ModelResult:
        full_inc, outputs = self.renew(gen_mean, gen_sd, proc, cdr, rt_init, prop_immune)
        cases = self.get_output_from_inc(full_inc, report_mean, report_sd, cdr)
        outputs["cases"] = cases[self.init_length :]
        deaths = self.get_output_from_inc(full_inc, death_mean, death_sd, ifr)
        outputs["deaths"] = deaths[self.init_length :]
        admissions = self.get_output_from_inc(full_inc, admit_mean, admit_sd, har)
        outputs["admissions"] = admissions[self.init_length :]
        occupancy = self.get_hosp_occupancy_from_admits(admissions, stay_mean, stay_sd)
        outputs["occupancy"] = occupancy[self.init_length :]
        weekly_cases = self.get_period_output_from_daily(cases, 7)
        outputs["weekly_cases"] = weekly_cases[self.init_length :]
        weekly_deaths = self.get_period_output_from_daily(deaths, 7)
        outputs["weekly_deaths"] = weekly_deaths[self.init_length :]
        seropos = (self.pop - outputs["suscept"]) / self.pop
        outputs["seropos"] = seropos
        return outputs


class MultiStrainModel(RenewalHospModel):

    def __init__(
        self,
        population,
        start,
        end,
        proc_update_freq,
        proc_fitter,
        dens_obj,
        window_len,
        init_series,
        reporting_dist,
        discharge_dens,
        strains,
        start_strain,
        seed_times,
        seed_rate,
        mobility,
    ):
        super().__init__(
            population,
            start,
            end,
            proc_update_freq,
            proc_fitter,
            dens_obj,
            window_len,
            init_series,
            reporting_dist,
            discharge_dens,
        )
        assert start_strain in strains, "Start strain not among modelled strains"
        self.strains = strains
        self.n_strains = len(strains)
        self.strain_map = get_combs(len(strains))
        self.dests = get_dests(self.strain_map)
        self.trans_mats = get_trans_mats(self.dests)
        self.rel_infectiousness = jnp.array([1.0] * self.n_strains)  # Relative infectiousness
        if mobility is None:
            self.mobility = jnp.ones_like(self.model_times)
        else:
            mobility.index = self.epoch.dti_to_index(mobility.index)
            self.mobility = jnp.array(mobility.loc[self.start :])

        no_seed = jnp.zeros([self.n_strains - 1, self.init_length])  # Zeros for the other strains
        init_seed = jnp.vstack([self.init_series, no_seed])  # Combine with seeding for first strain
        seed_vals = self.get_seeds(seed_times, seed_rate)  # Seeding during main period
        self.seeding = jnp.hstack([init_seed, seed_vals])  # Join together

    def date_to_index(self, date):
        return int(self.epoch.datetime_to_number(date))

    def get_seeds(
        self,
        seed_times: List[datetime.date],
        seed_rate: float,
    ) -> Array:
        """Convert seed requests to seeding values array.

        Args:
            seed_times: List of length one less than number of strains
                with each element representing the strains other than the start strain,
                and each element containing two elements representing the start
                and end time for the seeding process.
            seed_rate: The rate at which new people are introduced.

        Returns:
            Jaxified seeding rate array
        """
        seed_vals = np.zeros([self.n_strains, len(self.model_times)])
        for s in range(self.n_strains - 1):
            strain_seed_times = seed_times[s]
            seed_start = self.date_to_index(strain_seed_times[0])
            seed_end = self.date_to_index(strain_seed_times[1])
            seed_vals[s + 1, seed_start:seed_end] = seed_rate
        return jnp.array(seed_vals)

    def renew(self, mean, sd, proc, init, cross_immunity, inc_seeding):
        densities = self.dens_obj.get_densities(self.window_len, mean, sd)  # Generation densities
        process_vals = self.fit_process_curve(proc, init)  # Variable process
        init_inc = jnp.fliplr(inc_seeding[:, : self.init_length])  # Reverse initialisation
        start_pop = self.pop - jnp.sum(init_inc)  # Starting susceptible population
        start_pops = jnp.zeros(self.strain_map.shape[1])  # Starting susceptible distribution
        start_pops = start_pops.at[0].set(start_pop)
        full_suscept = jnp.ones_like(self.strain_map).astype(
            float
        )  # Start fully susceptible (array of shape n_strains X 2**n_strains)
        cross_imm = (
            jnp.array(self.strain_map).astype(float) * cross_immunity
        )  # Subtract immunity if you have been infected with that strain before (array of shape n_strains X 2**n_strains)
        suscept_levels = full_suscept - cross_imm  # Final susceptibility levels

        init_zeroes = jnp.zeros([self.n_strains, self.window_len])
        seeding_array = jnp.concat([init_zeroes, self.seeding[:, self.init_length :]], axis=1)

        def state_update(state: MultistrainState, t) -> tuple[MultistrainState, jnp.array]:
            proc_val = process_vals[t - self.start]  # Variable process (scalar)
            mob_val = self.mobility[t]  # Mobility data (scalar)

            # new_seed_vals = seeding_array[:, t - self.window_len : t]

            new_seed_vals = lax.dynamic_slice_in_dim(
                seeding_array, t - self.window_len, self.window_len, axis=1
            )

            new_inc = state.incidence + new_seed_vals

            contributions = (densities * new_inc).sum(
                axis=1
            )  # Incidence convolved with generation (vector of length n_strains)
            seed = inc_seeding[
                :, t + self.init_length
            ]  # Seeding by total effective infectious persons (vector of length n_strains)
            target_inf_rate = (
                (contributions + seed) * proc_val * mob_val * self.rel_infectiousness / self.pop
            )  # Infection rate (vector of length n_strains)
            total_inf_rates = target_inf_rate.sum()  # Total infection rates across all strains
            modifier = (
                1.0 - jnp.exp(-total_inf_rates)
            ) / total_inf_rates  # Modification needed to ensure the total rate of infection in one day is no more than one
            inf_rate = (
                target_inf_rate * modifier
            )  # The actual infection rate for each strain (array of shape n_strains X window_len)
            effect_suscepts = (
                suscept_levels * state.suscept
            )  # Effective susceptibles (array of shape n_strains X 2**n_strains)
            actual_inc = (
                effect_suscepts * inf_rate[:, jnp.newaxis]
            )  # Apply infection rates across susceptible categories (array of shape n_strains X 2**n_strains)
            suscept = state.suscept  # Population distribution (vector of length 2**n_strains)
            for s in range(self.n_strains):  # Move susceptibles to recovered categories
                suscept = suscept + actual_inc[s] @ self.trans_mats[s]
            strain_inc = actual_inc.sum(axis=1)  # Incidence by strain (vector of length n_strains)
            inc = jnp.concat(
                [strain_inc[:, jnp.newaxis], state.incidence[:, :-1]], axis=1
            )  # Move up (array of shape n_strains X window_len)
            strain_out = {
                strain: strain_inc[i_strain] for i_strain, strain in enumerate(self.strains)
            }
            suscept_out = {f"sus_{i}": suscept[i] for i in range(self.strain_map.shape[1])}
            return MultistrainState(inc, suscept), {"process": proc_val} | strain_out | suscept_out

        end_state, outputs = lax.scan(
            state_update, MultistrainState(init_inc, start_pops), self.model_times
        )
        return outputs

    def renewal_func(
        self,
        proc: List[float],
        gen_mean: float,
        gen_sd: float,
        cdr: float,
        ifr: float,
        rt_init: float,
        report_mean: float,
        report_sd: float,
        death_mean: float,
        death_sd: float,
        admit_mean: float,
        admit_sd: float,
        stay_mean: float,
        stay_sd: float,
        har: float,
        cross_immunity: float,
        **kwargs,
    ) -> ModelResult:
        inc_seeding = self.seeding / cdr
        start_inc = jnp.sum(self.seeding[:, : self.init_length], axis=0)
        outputs = self.renew(gen_mean, gen_sd, proc, rt_init, cross_immunity, inc_seeding)
        strain_inc = jnp.array([outputs[strain] for strain in self.strains])
        full_inc = jnp.concatenate([start_inc, jnp.array(strain_inc.sum(axis=0))])
        outputs["inc"] = full_inc[self.init_length :]
        cases = self.get_output_from_inc(full_inc, report_mean, report_sd, cdr)
        outputs["cases"] = cases[self.init_length :]
        deaths = self.get_output_from_inc(full_inc, death_mean, death_sd, ifr)
        outputs["deaths"] = deaths[self.init_length :]
        admissions = self.get_output_from_inc(full_inc, admit_mean, admit_sd, har)
        outputs["admissions"] = admissions[self.init_length :]
        occupancy = self.get_hosp_occupancy_from_admits(admissions, stay_mean, stay_sd)
        outputs["occupancy"] = occupancy[self.init_length :]
        weekly_cases = self.get_period_output_from_daily(cases, 7)
        outputs["weekly_cases"] = weekly_cases[self.init_length :]
        weekly_deaths = self.get_period_output_from_daily(deaths, 7)
        outputs["weekly_deaths"] = weekly_deaths[self.init_length :]
        outputs["seropos"] = (self.pop - outputs["sus_0"]) / self.pop
        strain_props = {
            f"prop_{strain}": outputs[strain] / outputs["inc"] for strain in self.strains
        }
        return outputs | strain_props
