from typing import List, Optional
from typing import NamedTuple
from warnings import warn

from jax import lax, vmap, Array, numpy as jnp
from jax.experimental import sparse
from datetime import datetime
import numpy as np
import pandas as pd
import copy

from summer2.utils import Epoch

from emu_renewal.process import sinterp, MultiCurve
from emu_renewal.distributions import Dens
from emu_renewal.utils import (
    format_date_for_str,
    round_sigfig,
    get_combs,
    get_col_increases,
    get_reset_array_from_increases,
)
from emu_renewal.mobility import MobilityProvider


ModelResult = dict[str, Array]


def get_dests(
    strain_map: np.ndarray,
) -> np.ndarray:
    """For a given set of immunity combinations
    (generated by get_combs), create a matrix (dests)
    that specifies which immunity profile you would
    transition to if infected by the strain represented by
    the row of the matrix.

    Example:
        First row of strain_map is [False, False] and
        second row is [False, True], element [0, 1]
        of dests will be 1.

    Args:
        strain_map: The possible immunity combinations

    Returns:
        The matrix described above
    """
    dests = np.zeros_like(strain_map, dtype=int)

    # Iterate through strains (rows of dests matrix)
    for s in range(strain_map.shape[0]):

        # Iterate through columns of matrix
        for i, imm in enumerate(strain_map.T):

            # Destination strain history
            dest = copy.copy(imm)
            dest[s] = True

            # Find its location within the mapping matrix
            dests[s, i] = np.where((strain_map == dest[:, None]).all(axis=0))[0][0]

    return dests


def get_trans_mats(dests: np.ndarray):
    """Get transition matrix for moving population
    based on destinations specified in get_dests above.

    Args:
        dests: Destination matrix

    Returns:
        Transition matrix
    """
    n_strains = dests.shape[0]
    n_rec_groups = dests.shape[1]
    trans_mats = []
    for s in range(n_strains):
        trans_mat = np.zeros((n_rec_groups, n_rec_groups))
        for source, dest in enumerate(dests[s]):
            trans_mat[source, dest] += 1.0
            trans_mat[source, source] -= 1.0
        trans_mats.append(sparse.BCOO.fromdense(trans_mat))
    return trans_mats


def is_val_nonneg(val):
    return jnp.min(jnp.array([jnp.sign(val) + 1.0, 1.0]))


class MultistrainState(NamedTuple):
    incidence: jnp.array
    suscept: jnp.array


class MultiStrainModel:

    def __init__(
        self,
        population: float,
        start: datetime,
        end: datetime,
        proc_update_freq: int,
        proc_fitter: MultiCurve,
        dens_obj: Dens,
        window_len: int,
        init_length: int,
        reporting_dist: Dens,
        discharge_dens: Dens,
        strains: List[str],
        start_strain: str,
        seed_times: List[datetime],
        mobility: MobilityProvider,
        seed_duration: int,
    ):
        """Construct the object for running the renewal process.

        Args:
            population: Number of people considered in the analysis
            start: Time to run the model from
            end: Time to run the model until
            proc_update_freq: Frequency to adjust the variable process
            proc_fitter: Method for fitting a curve to the points in the variable process
            dens_obj: Distribution for the renewal process
            window_len: How far back to go with the sliding window
            init_length: Initialisation period
            reporting_dist: Distribution for the time from infection to case reporting
            discharge_dens: Distribution for the time from hospital admission to discharge
            strains: Names of the variants to be implemented
            start_strain: Which of the variants to consider as the first strain
            seed_times: Times to seed each variant (including the first one)
            mobility: The mobility time series to scale transmission with
            seed_duration: The duration of seeding new variants
        """
        assert start_strain in strains, "Start strain not among modelled strains"
        self.strains = strains
        self.n_strains = len(strains)
        self.strain_map = get_combs(len(strains))
        self.dests = get_dests(self.strain_map)
        self.trans_mats = get_trans_mats(self.dests)
        self.seed_times = seed_times
        self.seed_duration = seed_duration
        self.discharge_dens = discharge_dens
        self.init_length = init_length

        # Times
        self.epoch = Epoch(start)
        self.start = int(self.epoch.dti_to_index(start))
        self.end = int(self.epoch.dti_to_index(end))
        self.model_times = jnp.arange(self.start, self.end + 1)
        self.description = {
            "Fixed parameters": (
                f"The main analysis period runs from {format_date_for_str(start)} "
                f"to {format_date_for_str(end)}, "
                f"with a preceding initialisation period of {self.init_length} days. "
            )
        }

        self.mob_provider = mobility
        self.mob_provider.reconcile_times(start, end)

        # Population
        self.pop = population
        self.description[
            "Fixed parameters"
        ] += f"The starting model population is {round_sigfig(population / 1e6, 2)} million persons. "

        # Process
        self.proc_update_freq = proc_update_freq
        self.x_proc_vals = jnp.arange(self.end, self.start, -self.proc_update_freq)[::-1]
        self.x_proc_data = sinterp.get_scale_data(self.x_proc_vals)
        self.proc_fitter = proc_fitter
        self.process_start = int(self.x_proc_vals[0])
        self.description["Variable process"] = (
            "Each x-value for the requested points in the variable process "
            "are set at evenly spaced intervals through the analysis period "
            f"spaced by {self.proc_update_freq} days and "
            "ending at the analysis end time. "
        )
        if self.start < self.process_start:
            self.description["Variable process"] = (
                "Because the analysis period is not an exact multiple "
                "of the duration of a process interval, "
                "the variable process only starts from day "
                f"{self.process_start} of the analysis. "
            )
        self.describe_process()

        # Generation interval
        self.dens_obj = dens_obj
        self.description["Generation times"] = self.dens_obj.get_desc()
        self.window_len = window_len
        self.description["Generation times"] += (
            "The generation interval for all calculations "
            f"is truncated from {window_len} days onwards "
            "on the assumption that the distribution's density "
            "has reached negligible values once this period has elapsed. "
        )

        # Renewal process
        self.describe_renewal()

        # Reporting delay
        self.report_dist = reporting_dist
        self.describe_reporting()
        self.description["Reporting"] += self.report_dist.get_desc()
        self.describe_weekly_sum()

    def renew(self, mean, sd, proc, init, cross_immunity, rel_infect, seed_rates, **kwargs):
        densities = self.dens_obj.get_densities(self.window_len, mean, sd)  # Generation densities
        process_vals = self.fit_process_curve(proc, init)  # Variable process
        init_inc = jnp.fliplr(self.seed_array[:, : self.init_length])  # Reverse initialisation
        start_pop = self.pop - jnp.sum(init_inc)  # Starting susceptible population
        start_pops = jnp.zeros(self.strain_map.shape[1])  # Starting susceptible distribution
        start_pops = start_pops.at[0].set(start_pop)
        if rel_infect is not None:
            rel_infect = jnp.concat([jnp.array([1.0]), rel_infect])
        else:
            rel_infect = 1.0

        # Cross immunity if previously infected with a different strain, otherwise zero (complete immunity) if infected with that strain
        suscept_levels = (~jnp.array(self.strain_map)).astype(float) * (1.0 - cross_immunity)
        # Complete susceptibility if never infected before
        suscept_levels = suscept_levels.at[:, 0].set(1.0)

        # Forbid reinfection with earlier strains after later emerging ones
        earlier_strain = get_col_increases(self.strain_map)
        reset_array = get_reset_array_from_increases(earlier_strain)
        suscept_levels = suscept_levels * (~reset_array).astype(float)

        mobility = self.mob_provider.get_parameterised_mobility(**kwargs)

        half_dur = self.seed_duration / 2.0
        # Not sure why this has to be minus one
        seed_starts = [-1.0] + [self.epoch.dti_to_index(s) for s in self.seed_times]
        seed_peaks = jnp.array(seed_starts) + half_dur

        def state_update(state: MultistrainState, t) -> tuple[MultistrainState, jnp.array]:
            proc_val = process_vals[t - self.start]  # Variable process (scalar)
            mob_val = mobility[t - self.start]  # Mobility data (scalar)
            # Incidence history (array of shape n_strains X window_len)
            rel_seed_vals = 1.0 - abs(t - seed_peaks) / half_dur
            zeroed_seed_vals = jnp.where(rel_seed_vals > 0.0, rel_seed_vals, 0.0)
            seed_vals = jnp.multiply(zeroed_seed_vals, seed_rates * self.pop)
            past_inc = state.incidence.at[:, 0].set(state.incidence[:, 0] + seed_vals)
            # Incidence convolved with generation (vector of length n_strains)
            contributions = (densities * past_inc).sum(axis=1)
            # Infection rate (vector of length n_strains)
            target_inf_rates = contributions * proc_val * mob_val * rel_infect / self.pop
            # Ceiling in case of very high incidence rates within a given day (vector of length n_strains)
            actual_inf_rate = 1.0 - jnp.exp(-target_inf_rates)
            # Effective susceptibles (array of shape n_strains X 2**n_strains)
            effect_suscepts = suscept_levels * state.suscept
            # Apply infection rates across susceptible categories (array of shape n_strains X 2**n_strains)
            actual_inc = effect_suscepts * actual_inf_rate[:, jnp.newaxis]
            suscept = state.suscept  # Population distribution (vector of length 2**n_strains)
            for s in range(self.n_strains):  # Move susceptibles to recovered categories
                suscept += actual_inc[s] @ self.trans_mats[s]
            strain_inc = actual_inc.sum(axis=1)  # Incidence by strain (vector of length n_strains)
            # Move up (array of shape n_strains X window_len)
            inc = jnp.concat([strain_inc[:, jnp.newaxis], past_inc[:, :-1]], axis=1)
            strain_out = {s: strain_inc[i_strain] for i_strain, s in enumerate(self.strains)}
            suscept_out = {f"sus_{i}": suscept[i] for i in range(self.strain_map.shape[1])}
            return MultistrainState(inc, suscept), {"process": proc_val} | strain_out | suscept_out

        end_state, outputs = lax.scan(
            state_update, MultistrainState(init_inc, start_pops), self.model_times
        )
        return outputs

    def fit_process_curve(
        self,
        y_proc_req: List[float],
        rt_init,
    ) -> jnp.array:
        """See describe_process below.

        Args:
            y_proc_req: The submitted log values for the variable process

        Returns:
            The values of the variable process at each model time
        """
        y_proc_vals = jnp.cumsum(jnp.concatenate([jnp.array((rt_init,)), y_proc_req]))
        y_proc_data = sinterp.get_scale_data(y_proc_vals)
        cos_func = vmap(self.proc_fitter.get_multicurve, in_axes=(0, None, None))
        return jnp.exp(cos_func(self.model_times, self.x_proc_data, y_proc_data))

    def describe_process(self):
        self.description["Variable process"] += self.proc_fitter.get_description()
        self.description["Variable process"] += (
            "The parameters for the variable process are explored as "
            "the update of each process value relative to the preceding value. "
            "Each of the parameters for the variable process is exponentiated, "
            "such that these parameters are explored in the log-transformed space. "
        )

    def describe_renewal(self):
        self.description["Renewal process"] = (
            "Calculation of the renewal process "
            "consists of multiplying the incidence values for the preceding days "
            "by the reversed generation time distribution values. "
            "This follows a standard formula, "
            "described elsewhere by several groups,[@cori2013; @faria2021] i.e. "
            "$$i_t = R_t\sum_{\\tau<t} i_\\tau g_{t-\\tau}$$\n"
            "$R_t$ is calculated as the product of the proportion "
            "of the population remaining susceptible "
            "and the non-mechanistic random process "
            "generated external to the renewal model. "
            "The susceptible population is calculated by "
            "subtracting the number of new incident cases from the "
            "running total of susceptibles at each iteration. "
            "If incidence exceeds the number of susceptible persons available "
            "for infection in the model, incidence is capped at the "
            "remaining number of susceptibles. "
        )

    def renewal_func(
        self,
        proc: List[float],
        gen_mean: float,
        gen_sd: float,
        cdr: float,
        ifr: float,
        rt_init: float,
        report_mean: float,
        report_sd: float,
        death_mean: float,
        death_sd: float,
        admit_mean: float,
        admit_sd: float,
        stay_mean: float,
        stay_sd: float,
        har: float,
        icu_admit_mean: float,
        icu_admit_sd: float,
        icu_stay_mean: float,
        icu_stay_sd: float,
        icu_ar: float,
        cross_immunity: float,
        seed_rates: List[float],
        relinfect: Optional[List[float]],
        **kwargs,
    ) -> ModelResult:
        self.seed_array = jnp.zeros([self.n_strains, self.init_length + len(self.model_times)])
        start_inc = jnp.sum(self.seed_array[:, : self.init_length], axis=0)
        outputs = self.renew(gen_mean, gen_sd, proc, rt_init, cross_immunity, relinfect, seed_rates, **kwargs)
        strain_inc = jnp.array([outputs[strain] for strain in self.strains])
        full_inc = jnp.concatenate([start_inc, jnp.array(strain_inc.sum(axis=0))])
        outputs["inc"] = full_inc[self.init_length :]

        cases = self.get_output_from_inc(full_inc, report_mean, report_sd, cdr)
        outputs["cases"] = cases[self.init_length :]
        weekly_cases = self.get_period_output_from_daily(cases, 7)
        outputs["weekly_cases"] = weekly_cases[self.init_length :]

        deaths = self.get_output_from_inc(full_inc, death_mean, death_sd, ifr)
        outputs["deaths"] = deaths[self.init_length :]
        weekly_deaths = self.get_period_output_from_daily(deaths, 7)
        outputs["weekly_deaths"] = weekly_deaths[self.init_length :]

        admissions = self.get_output_from_inc(full_inc, admit_mean, admit_sd, har)
        outputs["admissions"] = admissions[self.init_length :]
        weekly_admissions = self.get_period_output_from_daily(admissions, 7)
        outputs["weekly_admissions"] = weekly_admissions[self.init_length :]
        occupancy = self.get_hosp_occupancy_from_admits(admissions, stay_mean, stay_sd)
        outputs["occupancy"] = occupancy[self.init_length :]

        icu_admits = self.get_output_from_inc(full_inc, icu_admit_mean, icu_admit_sd, har * icu_ar)
        outputs["icu_admissions"] = icu_admits[self.init_length :]
        icu_weekly_admissions = self.get_period_output_from_daily(icu_admits, 7)
        outputs["icu_weekly_admissions"] = icu_weekly_admissions[self.init_length :]
        icu_occupancy = self.get_hosp_occupancy_from_admits(icu_admits, icu_stay_mean, icu_stay_sd)
        outputs["icu_occupancy"] = icu_occupancy[self.init_length :]

        outputs["seropos"] = (self.pop - outputs["sus_0"]) / self.pop
        strain_props = {f"prop_{s}": outputs[s] / outputs["inc"] for s in self.strains}
        return outputs | strain_props

    def get_output_from_inc(
        self,
        full_inc: jnp.array,
        report_mean: float,
        report_sd: float,
        cdr: float,
    ) -> jnp.array:
        """Apply an observation model as a convolution to calculate an epidemiological output series.

        Args:
            full_inc: The full incidence series including the initialisation
            report_mean: Mean delay to reporting
            report_sd: Standard deviation of delay to reporting
            cdr: Case detection/ascertainment proportion

        Returns:
            Output from start of initialisation to end of model time
        """
        densities = self.dens_obj.get_densities(self.window_len, report_mean, report_sd)
        convolved_cases = jnp.convolve(full_inc, densities) * cdr
        return convolved_cases[: len(full_inc)]

    def describe_reporting(self):
        self.description["Reporting"] = (
            "Notifications are calculated by first convoling "
            "the probability distribution representing the time from "
            "onset of an infection episode to reporting with the "
            "time series of incidence. "
            "This is then multiplied through by the modelled "
            "case detection rate to obtain the final time series "
            "for case notifications. "
        )

    def get_period_output_from_daily(
        self,
        raw_series: jnp.array,
        n_sum_times: int,
    ) -> jnp.array:
        """Sum over a preceding window period to get counts over a period of time.

        Args:
            raw_series: Observations before windowing applied
            n_sum_times: Duration of period for summing

        Returns:
            Summed series
        """
        windower = jnp.array([1.0] * n_sum_times)
        return jnp.convolve(raw_series, windower)[: len(raw_series)]

    def describe_weekly_sum(self):
        self.description["Reporting"] += (
            "Last, weekly case counts are then calculated from this "
            "time series of notifications. "
        )

    def get_hosp_occupancy_from_admits(self, full_admits, stay_mean, stay_sd):
        discharge = 1.0 - self.discharge_dens.get_cum_dens(self.window_len, stay_mean, stay_sd)
        return jnp.convolve(full_admits, discharge)[: len(full_admits)]

    def get_description(self) -> str:
        """Compile the description of model.

        Returns:
            Description
        """
        description = ""
        for title, text in self.description.items():
            description += f"\n\n### {title}\n"
            description += text
        return description
